name: individual_camera_coffee_bean

image_shape: [3, 240, 320]
dataset_path: data/xarm_multi/individual_camera_10_10

shape_meta: &shape_meta
  # camera_2 is added here
  obs:
    camera_1:
      shape: ${task.image_shape}
      type: rgb
    camera_2:
      shape: ${task.image_shape}
      type: rgb
    camera_3:
      shape: ${task.image_shape}
      type: rgb
    camera_4:
      shape: ${task.image_shape}
      type: rgb
    arm1_robot_eef_pos:
      shape: [3]
      type: low_dim
    arm1_eef_quat:
      shape: [4]
      type: low_dim
    arm2_robot_eef_pos:
      shape: [3]
      type: low_dim
    arm2_eef_quat:
      shape: [4]
      type: low_dim
  arm1_action:
    shape: [10]
  arm2_action:
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.xarm_image_runner.XarmImageRunner

dataset:
  _target_: diffusion_policy.dataset.xarm_individual_camera_dataset.XarmIndividualCameraDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False
